language: php
dist: trusty
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

script:
  - 'curl -H "Accept: text/plain" https://security.symfony.com/check_lock -F lock=@./composer.lock'
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text
