name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install dependencies
              run: composer install --no-progress --no-suggest --no-interaction

            - name: Check coding standards
              run: ./vendor/bin/ecs check

            - name: Run PHPUnit tests
              run: ./vendor/bin/phpunit
